import {historicalEstimate} from './history.mjs';
import {discoverTokens} from './discovery.mjs';
import {capInUSD,entryTime} from './entry-fields.mjs';
import {accountEmail,displayAccount} from './accounts.mjs';
import {normalizeCA,manualCap,fetchQuotes} from './domain.mjs';
const enc=new TextEncoder();
const json=(data,status=200,headers={})=>Response.json(data,{status,headers:{'Cache-Control':'no-store',...headers}});
function fail(message,status=400){const e=new Error(message);e.status=status;throw e}
function cookie(req,name){return req.headers.get('cookie')?.split(';').map(s=>s.trim()).find(s=>s.startsWith(name+'='))?.slice(name.length+1)??''}
async function sign(text,secret){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return Array.from(new Uint8Array(await crypto.subtle.sign('HMAC',key,enc.encode(text)))).map(b=>b.toString(16).padStart(2,'0')).join('')}
export async function handle(req,env,fetcher=fetch){
 const url=new URL(req.url),path=url.pathname.replace(/^\/api\//,''),write=req.method!=='GET';
 const cfg={url:env.SUPABASE_URL?.replace(/\/$/,''),key:env.SUPABASE_ANON_KEY,service:env.SUPABASE_SECRET_KEY||env.SUPABASE_SERVICE_ROLE_KEY};
 const configured=Boolean(cfg.url&&cfg.key&&cfg.service);
 try{
 if(path==='config')return json({configured});
 if(!configured) return json({error:'尚未连接公共数据库，请按配置指引完成设置'},503);
 if(write&&req.headers.get('origin')!==url.origin)fail('请求来源不匹配',403);
 if(!['GET','POST'].includes(req.method))fail('不支持该请求方式',405);
 let body={};if(write){if(!req.headers.get('content-type')?.includes('application/json'))fail('需要 JSON 请求',415);const raw=await req.text();if(raw.length>30000)fail('请求内容过大',413);try{body=JSON.parse(raw)}catch{fail('无效 JSON')}if(!body||Array.isArray(body)||typeof body!=='object')fail('无效请求');}
 const sb=async(endpoint,method='GET',data,token='',service=false)=>{const key=service?cfg.service:cfg.key;const r=await fetcher(cfg.url+endpoint,{method,headers:{apikey:key,...((service?!cfg.service.startsWith('sb_secret_'):Boolean(token))?{Authorization:'Bearer '+(service?cfg.service:token)}:{}),'Content-Type':'application/json',Prefer:endpoint.startsWith('/rest/v1/favorites?on_conflict=')?'resolution=ignore-duplicates,return=minimal':'return=minimal'},body:data===undefined?undefined:JSON.stringify(data),signal:AbortSignal.timeout(10000)});if(!r.ok){if(r.status===401||r.status===403)fail('登录已过期或没有操作权限',401);fail('数据库请求失败，请检查连接和表结构',502)}const text=await r.text();return text?JSON.parse(text):null};
 const who=async()=>{const token=cookie(req,'wb_access');if(!token)return null;try{const u=await sb('/auth/v1/user','GET',undefined,token);const member=await sb('/rest/v1/members?select=role,enabled&user_id=eq.'+u.id,'GET',undefined,token);return member?.[0]?.enabled?{id:u.id,email:u.email,role:member[0].role,token}:null}catch(e){if(e.status===401)return null;throw e}};
 const requireUser=async()=>{const u=await who();if(!u)fail('请先登录有效成员账号',401);return u};
 const cookies=(access,refresh,seconds=3600)=>{const h=new Headers({'Cache-Control':'no-store'});const secure=url.protocol==='https:'?'; Secure':'';h.append('Set-Cookie','wb_access='+access+'; HttpOnly; SameSite=Strict; Path=/; Max-Age='+seconds+secure);h.append('Set-Cookie','wb_refresh='+refresh+'; HttpOnly; SameSite=Strict; Path=/api/; Max-Age='+(refresh?604800:0)+secure);return h};
 if(path==='login'&&write){if(typeof body.email!=='string'||typeof body.password!=='string')fail('请输入账号和密码');const d=await sb('/auth/v1/token?grant_type=password','POST',{email:accountEmail(body.email),password:body.password});const members=await sb('/rest/v1/members?select=enabled&user_id=eq.'+d.user.id,'GET',undefined,d.access_token);if(!members?.[0]?.enabled)fail('该账号尚未加入看板成员',403);return Response.json({ok:true},{headers:cookies(d.access_token,d.refresh_token,d.expires_in)})}
 if(path==='session'&&write){const refresh=cookie(req,'wb_refresh');if(!refresh)return json({ok:false});try{const d=await sb('/auth/v1/token?grant_type=refresh_token','POST',{refresh_token:refresh});return Response.json({ok:true},{headers:cookies(d.access_token,d.refresh_token,d.expires_in)})}catch{return Response.json({ok:false},{headers:cookies('','',0)})}}
 if(path==='logout'&&write){const token=cookie(req,'wb_access');if(token){try{await sb('/auth/v1/logout','POST',{},token)}catch{/* Always clear local session. */}}return Response.json({ok:true},{headers:cookies('','',0)})}
 if(path==='password'&&write){const u=await requireUser();if(typeof body.password!=='string'||body.password.length<12)fail('新密码至少 12 位');await sb('/auth/v1/user','PUT',{password:body.password},u.token);return json({ok:true})}
 if(path==='version'&&!write){const d=await sb('/rest/v1/board_state?select=version&id=eq.1');return json({version:String(d[0].version)})}
 if(path==='board'&&!write){const d=await sb('/rest/v1/rpc/read_board','POST',{});const expiry=Math.floor(Date.now()/1000)+604800;for(const t of d.tokens){t.proof=expiry+'.'+await sign(t.chain+':'+t.ca+':'+expiry,cfg.service)}return json(d)}
 if(path==='me'&&!write){const u=await who();if(!u)return json({user:null,favorites:[]});const f=await sb('/rest/v1/favorites?select=token_id&user_id=eq.'+u.id,'GET',undefined,u.token);return json({user:{email:displayAccount(u.email),role:u.role},favorites:f.map(x=>x.token_id)})}
 if(path==='quotes'&&write){if(!Array.isArray(body.addresses)||body.addresses.length<1||body.addresses.length>30||!Array.isArray(body.proofs)||body.proofs.length!==body.addresses.length)fail('无效行情批次');for(let i=0;i<body.addresses.length;i++){const ca=normalizeCA(body.chain,body.addresses[i]);const proof=String(body.proofs[i]);const [expiry,sig]=proof.split('.');if(!/^\d{10}$/.test(expiry)||Number(expiry)<Date.now()/1000||sig!==await sign(body.chain+':'+ca+':'+expiry,cfg.service))fail('列表凭据已失效，请重新同步列表',403)}return json({quotes:await fetchQuotes(body.chain,body.addresses,fetcher)})}
 const verifyEstimate=async(chain,ca,createdAt,cap)=>{if(!body.estimate)return null;const packet=body.estimate;if(!packet.data||typeof packet.signature!=='string'||packet.signature!==await sign(JSON.stringify(packet.data),cfg.service))fail('估算凭据无效，请重新查询');const d=packet.data;if(d.chain!==chain||d.ca!==ca||d.requestedAt!==createdAt||Number(d.amount)!==Number(cap))fail('估算信息已变化，请重新查询或手动填写');return d};
 if(path==='history'&&write){await requireUser();const data=await historicalEstimate(body.chain,body.ca,body.createdAt,fetcher);return json({estimate:{data,signature:await sign(JSON.stringify(data),cfg.service)}})}
 if(path==='discover'&&write){await requireUser();return json({candidates:await discoverTokens(body.ca,fetcher)})}
 if(path==='tokens'&&write){const u=await requireUser();const ca=normalizeCA(body.chain,body.ca),cap=body.capValue!==undefined?capInUSD(body.capValue,body.capUnit??'K'):manualCap(body.manualMarketCap);const old=await sb('/rest/v1/tokens?select=id&chain=eq.'+body.chain+'&ca=eq.'+ca);if(old.length)return json({id:old[0].id,existing:true});let q=null;try{q=(await fetchQuotes(body.chain,[ca],fetcher))[0]}catch{/* Keep unknown baseline, never fill it with a future quote. */}const createdAt=entryTime(body.createdAt);if(createdAt&&Date.parse(createdAt)>Date.now())fail('收录时间不能晚于当前时间');const estimate=await verifyEstimate(body.chain,ca,createdAt,cap);const d=await sb('/rest/v1/rpc/add_token_v3','POST',{p_actor:u.id,p_chain:body.chain,p_ca:ca,p_name:q?.name??'',p_symbol:q?.symbol??'',p_cap:cap||(createdAt?null:(q?.marketCap??null)),p_source:estimate?'estimated':cap?'manual':!createdAt&&q?.marketCap?'auto':'unavailable',p_fetched:estimate?.referenceAt??(!createdAt?q?.fetchedAt:null)??null,p_pair:estimate?.pool??(!createdAt?q?.pair:null)??null,p_created:createdAt,p_estimate:estimate},'',true);return json(d)}
 if(path==='favorites'&&write){const u=await requireUser();if(!/^[0-9a-f-]{36}$/.test(body.id)||typeof body.enabled!=='boolean')fail('无效收藏请求');await sb(body.enabled?'/rest/v1/favorites?on_conflict=user_id,token_id':'/rest/v1/favorites?user_id=eq.'+u.id+'&token_id=eq.'+body.id,body.enabled?'POST':'DELETE',body.enabled?{user_id:u.id,token_id:body.id}:undefined,u.token);return json({ok:true})}
 if((path==='edit'||path==='delete')&&write){const u=await requireUser();if(u.role!=='admin')fail('仅管理员可编辑或删除',403);if(!/^[0-9a-f-]{36}$/.test(body.id))fail('无效记录');if(path==='delete'){if(body.confirmed!==true)fail('请先确认删除');await sb('/rest/v1/rpc/delete_token','POST',{p_actor:u.id,p_id:body.id},'',true)}else{const time=entryTime(body.createdAt);if(!time)fail('收录时间不能为空');const cap=capInUSD(body.capValue,body.capUnit??'K');const old=await sb('/rest/v1/tokens?select=chain,ca&id=eq.'+body.id);if(!old[0])fail('记录不存在',404);const estimate=await verifyEstimate(old[0].chain,old[0].ca,time,cap);await sb('/rest/v1/rpc/edit_token_v2','POST',{p_actor:u.id,p_id:body.id,p_created:time,p_cap:cap||null,p_estimate:estimate,p_manual:body.capChanged===true},'',true)}return json({ok:true})}
 return json({error:'接口不存在'},404);
 }catch(e){return json({error:e.message??'请求失败'},e.status??400,e.retryAfter?{'Retry-After':String(e.retryAfter)}:{})}
}
